import os
import sqlite3
import pandas as pd
import google.generativeai as genai
from dotenv import load_dotenv


load_dotenv()


class NL2SQLService:
    """
    Service responsible for converting
    natural language questions into SQL queries.
    """

    def __init__(self, db_path: str):

        self.db_path = db_path

        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise ValueError("GEMINI_API_KEY not found in environment variables")

        genai.configure(api_key=api_key)

        self.model = genai.GenerativeModel("models/gemini-2.5-flash")

    def _get_schema(self):
        """
        Extract database schema for prompting.
        """

        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = cursor.fetchall()

        schema = ""

        for table in tables:

            table_name = table[0]

            cursor.execute(f"PRAGMA table_info({table_name});")
            columns = cursor.fetchall()

            schema += f"\nTable: {table_name}\n"

            for col in columns:
                schema += f"{col[1]} ({col[2]})\n"

        conn.close()

        return schema

    def _clean_sql(self, sql: str) -> str:
        """
        Clean SQL generated by LLM.
        Removes markdown, labels, and extra text.
        """

        sql = sql.strip()

        # remove markdown formatting
        sql = sql.replace("```sql", "")
        sql = sql.replace("```", "")

        # remove labels sometimes returned by LLM
        if sql.lower().startswith("sqlite"):
            sql = sql[6:]

        if sql.lower().startswith("sql"):
            sql = sql[3:]

        # ensure query starts from SELECT
        select_index = sql.lower().find("select")

        if select_index != -1:
            sql = sql[select_index:]

        return sql.strip()

    def _validate_sql(self, sql: str):
        """
        Prevent dangerous SQL queries.
        Only allow SELECT queries.
        """

        sql_lower = sql.lower()

        forbidden_keywords = ["drop", "delete", "update", "insert", "alter"]

        for keyword in forbidden_keywords:
            if keyword in sql_lower:
                raise ValueError("Unsafe SQL query generated.")

        if not sql_lower.startswith("select"):
            raise ValueError("Only SELECT queries are allowed.")

    def generate_sql(self, question: str):
        """
        Convert natural language question into SQL query.
        """

        schema = self._get_schema()

        prompt = f"""
You are a SQL expert.

Convert the following natural language question into a valid SQLite SQL query.

Database Schema:
{schema}

Question:
{question}

Return ONLY the SQL query.
"""

        response = self.model.generate_content(prompt)

        sql_query = response.text.strip()

        sql_query = self._clean_sql(sql_query)

        return sql_query

    def run_query(self, sql_query: str):
        """
        Execute SQL query and return results.
        """

        self._validate_sql(sql_query)

        conn = sqlite3.connect(self.db_path)

        df = pd.read_sql_query(sql_query, conn)

        conn.close()

        return df.to_dict(orient="records")